name: Publish release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: gradle -Pversion=${{ github.event.release.tag_name }} -Pargs='jmix.qiniufs.accessKey=${{ secrets.JMIX_QINIUFS_ACCESSKEY }} ,--jmix.qiniuifs.secretAccessKey=${{ secrets.JMIX_QINIUFS_SECRETACCESSKEY }}' build publish
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ github.token }}